export const TransactionsData = [{
    "pay_id": "PAY-1",
    "ord_id": "ORD-4",
    "name": "Giriraj Sharma",
    "email": "gsharma0@cdbaby.com",
    "mode_of_payment": "Cash",
    "payment_date": "	28th July 2024",
    "transaction_amount":"$485.19",
    "phone_no": "9826497033",
  }, {
    "pay_id": "PAY-2",
    "ord_id": "ORD-3",
    "name": "Rajesh Sonavane",
    "email": "sonrajesh@sohu.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "	7th August 2024",
    "transaction_amount":"$42.36",
    "phone_no": "8116129950",
  }, {
    "pay_id": "PAY-3",
    "ord_id": "ORD-7",
    "name": "Sakshi Haste",
    "email": "sakshihaste@gmail.com",
    "mode_of_payment": "Debit Card",
    "payment_date": "10th June 2024",
    "transaction_amount":"$142.56",
    "phone_no": "9492220019",
  }, {
    "pay_id": "PAY-4",
    "ord_id": "ORD-6",
    "name": "Abhilasha Barod",
    "email": "abhishekb12@time.com",
    "mode_of_payment": "UPI",
    "payment_date": "9th June 2024",
    "transaction_amount":"$789.42",
    "phone_no": "7643601807",
  }, {
    "pay_id": "PAY-5",
    "ord_id":"ORD-5",
    "name": "Yash Bunny",
    "email": "yashnikam@gmail.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "9th June 2024",
    "transaction_amount":"$789.42",
    "phone_no": "8831329111",
  }, 
  {
    "pay_id": "PAY-6",
    "ord_id":"ORD-28",
    "name": "Mohini Tembure",
    "email": "mohintT@nymag.com",
    "mode_of_payment": "Cash",
    "payment_date": "1th January 2024",
    "transaction_amount":"$125.25",
    "phone_no": "9147530130",
  }, 
  {
    "pay_id": "PAY-7",
    "ord_id":"ORD-25",
    "name": "Raju Ghumade",
    "email": "chadlee7@yellowpages.com",
    "mode_of_payment": "UPI",
    "payment_date": "1th January 2024",
    "transaction_amount":"$111.59",
    "phone_no": "9375130404",
  }, 
  {
    "pay_id": "PAY-8",
    "ord_id":"ORD-27",
    "name": "Shailesh Ramapure",
    "email": "sramapure28@gmail.com",
    "mode_of_payment": "Debit Card",
    "payment_date": "	14th February 2024",
    "transaction_amount":"$784.69",
    "phone_no": "8686927931",
  }, {
    "pay_id": "PAY-9",
    "ord_id":"ORD-26",
    "name": "	Urvashi Balsagar",
    "email": "urvashibal45@rediffmail.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "23rd March 2024",
    "transaction_amount":"$965.02",
    "phone_no": "7634710515",
  }, {
    "pay_id": "PAY-10",
    "ord_id": "ORD-24",
    "name": "Priya Zansari",
    "email": "priyazansari@gmail.com",
    "mode_of_payment": "UPI",
    "payment_date": "23rd March 2024",
    "transaction_amount":"$783.59",
    "phone_no": "8942647383",
  }, {
    "pay_id": "PAY-11",
    "ord_id":"ORD-23",
    "name": "	Vasu Kahipura",
    "email": "kahipuravasu2@europa.eu",
    "mode_of_payment": "UPI",
    "payment_date": "1st March 2024",
    "transaction_amount":"$785.36",
    "phone_no": "9375429011",
  }, {
    "pay_id": "PAY-12",
    "ord_id":"ORD-21",
    "name": "Sai Badjata",
    "email": "dbootherstonec@census.com",
    "mode_of_payment": "Debit Card",
    "payment_date": "25th April 2024",
    "transaction_amount":"$485.89",
    "phone_no": "7512775893",
  }, {
    "pay_id": "PAY-13",
    "ord_id":"ORD-22",
    "name": "Arvind Rai",
    "email": "arvindraid@last.fm",
    "mode_of_payment": "Cash",
    "payment_date": "15th April 2024",
    "transaction_amount":"$485.89",
    "phone_no": "9758543747",
    "shipping_address": "18 Aparna, Jaiprakash Nagar, Nagpur 442103",
    "age": 35
  }, {
    "pay_id": "PAY-14",
    "ord_id":"ORD-20",
    "name": "Sahil Yadav",
    "email": "sahilyadav45@ehow.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "24th April 2024",
    "transaction_amount":"$623.25",
    "phone_no": "9183733755",
  }, {
    "pay_id": "PAY-15",
    "ord_id":"ORD-18",
    "name": "Akrant Sahu",
    "email": "sahuakrant@gmail.com",
    "mode_of_payment": "UPI",
    "payment_date": "23rd April 2024",
    "transaction_amount":"$593.24",
    "phone_no": "8732611315",
  }, {
    "pay_id": "PAY-16",
    "ord_id":"ORD-19",
    "name": "	Pratap Kadu",
    "email": "pratapkadu10@gmail.com",
    "mode_of_payment": "Debit Card",
    "payment_date": "28th May 2024",
    "transaction_amount":"	$521.96",
    "phone_no": "9493954278",
  }, {
    "pay_id": "PAY-17",
    "ord_id":"ORD-17",
    "name": "Rihana Patel",
    "email": "patelrihana@rediffmail.com",
    "mode_of_payment": "Cash",
    "payment_date": "29th May 2024",
    "transaction_amount":"$30.26",
    "phone_no": "9675312004",
  },{
    "pay_id": "PAY-18",
    "ord_id":"ORD-15",
    "name": "Shital Naik",
    "email": "shitalnaik23@gmail.com",
    "mode_of_payment": "UPI",
    "payment_date": "25th May 2024",
    "transaction_amount":"$654.68",
    "phone_no": "7376089954",
  },  {
    "pay_id": "PAY-19",
    "ord_id":"ORD-16",
    "name": "Rushi Carrol",
    "email": "rushicarol78@gmail.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "	29th May 2024",
    "transaction_amount":"$482.26",
    "phone_no": "9962307083",
  }, {
    "pay_id": "PAY-20",
    "ord_id":"ORD-14",
    "name": "Narayan Sukdeve",
    "email": "narayansukdeve@gmail.com",
    "mode_of_payment": "UPI",
    "payment_date": "	7th May 2024",
    "transaction_amount":"$235.69",
    "phone_no": "7294595379",
  },  {
    "pay_id": "PAY-21",
    "ord_id":"ORD-12",
    "name": "Rahul Parteki",
    "email": "rahulp@gmail.com",
    "mode_of_payment": "UPI",
    "payment_date": "23rd May 2024",
    "transaction_amount":"$482.23",
    "phone_no": "7822116649",
  },{
    "pay_id": "PAY-22",
    "ord_id":"ORD-11",
    "name": "Sayadi Rathod",
    "email": "sayadirathod7@gmail.com",
    "mode_of_payment": "Cash",
    "payment_date": "15th May 2024",
    "transaction_amount":"$412.89",
    "phone_no": "8694181627",
  },  {
    "pay_id": "PAY-23",
    "ord_id":"ORD-9",
    "name": "	Gayatri Kulkarni",
    "email": "kulkarnigayatri0@gmail.com",
    "mode_of_payment": "Debit Card",
    "payment_date": "8th June 2024",
    "transaction_amount":"	$0.26",
    "phone_no": "9744457113",
  }, {
    "pay_id": "PAY-24",
    "ord_id":"ORD-10",
    "name": "	Sangul Abdur",
    "email": "abdursangul@ifeng.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "13h May 2024",
    "transaction_amount":"$75.26",
    "phone_no": "9487125811",
  },  {
    "pay_id": "PAY-25",
    "ord_id":"ORD-2",
    "name": "Riya Badhe",
    "email": "riyabadhell14@bbb.org",
    "mode_of_payment": "UPI",
    "payment_date": "	9th August 2024",
    "transaction_amount":"$532.36",
    "phone_no": "9769076278",
  }, {
    "pay_id": "PAY-26",
    "ord_id":"ORD-1",
    "name": "Shaili Zhodape",
    "email": "shailizhodape49@gmail.com",
    "mode_of_payment": "Credit Card",
    "payment_date": "19th August 2024",
    "transaction_amount":"	$759.26",
    "phone_no": "7956791749",
  },
]