export const RecentOrderData = [
    {
        id: "#1",
        product_id: "#1482",
        name: "Shaili Zhodape",
        orderDate: "19th August 2024",
        orderTotal: "$759.26",
        shippingAdress: "Omkar Nagar, Nagpur 48723",
        orderStatus: "PLACED",
    },
    {
        id: "#2",
        product_id: "#2145",
        name: "Riya Badhe",
        orderDate: "9th August 2024",
        orderTotal: "$532.36",
        shippingAdress: "Gandhi Bagh, Nagpur 44789",
        orderStatus: "CONFIRMED",
    },
    {
        id: "#3",
        product_id: "#8745",
        name: "Rajesh Sonavane",
        orderDate: "7th August 2024",
        orderTotal: "$42.36",
        shippingAdress: "Sikash Nagar, Firozpur 74589",
        orderStatus: "SHIPPED",
    },
    {
        id: "#4",
        product_id: "#1628",
        name: "Giriraj Sharma",
        orderDate: "28th July 2024",
        orderTotal: "$485.19",
        shippingAdress: "Gajanan Nagar, Gurgaon 44582",
        orderStatus: "OUT FOR DELIVERY",
    },  
    {
        id: "#5",
        product_id: "#1628",
        name: "Yash Bunny",
        orderDate: "8th June 2024",
        orderTotal: "$0.26",
        shippingAdress: "Surve Nagar, Gurgaon 44582",
        orderStatus: "DELIVERED",
    },
    {
        id: "#6",
        product_id: "#2547",
        name: "Abhilasha Barod",
        orderDate: "9th June 2024",
        orderTotal: "$789.42",
        shippingAdress: "Sahu Nagar, Delhi 47854",
        orderStatus: "SHIPPED",
    },
    {
        id: "#7",
        product_id: "#6524",
        name: "Sakshi Haste",
        orderDate: "10th June 2024",
        orderTotal: "$142.56",
        shippingAdress: "Suyesh Nagar, Kaniha 89652",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "#8",
        product_id: "#4100",
        name: "Rutvik Shinde",
        orderDate: "16th June 2024",
        orderTotal: "$236.02",
        shippingAdress: "Rajesh Nagar, Hydeabad 74523",
        orderStatus: "SHIPPED",
    },
    {
        id: "#9",
        product_id: "#7231",
        name: "Gayatri Kulkarni",
        orderDate: "8th June 2024",
        orderTotal: "$0.26",
        shippingAdress: "Surve, Gurgaon 44582",
        orderStatus: "CONFIRMED",
    },
    {
        id: "#10",
        product_id: "#1123",
        name: "Sangul Abdur",
        orderDate: "13h May 2024",
        orderTotal: "$75.26",
        shippingAdress: "Ashish Nagar, Gurgaon 36571",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "#11",
        product_id: "#1759",
        name: "Sayadi Rathod",
        orderDate: "15th May 2024",
        orderTotal: "$412.89",
        shippingAdress: "Kothavri, Talcher 58493",
        orderStatus: "SHIPPED",
    },
    {
        id: "#12",
        product_id: "#4324",
        name: "Rahul Parteki",
        orderDate: "23rd May 2024",
        orderTotal: "$482.23",
        shippingAdress: "Shanto Nagar, Gurgaon 44215",
        orderStatus: "DELIVERED",
    },
    {
        id: "#13",
        product_id: "#8435",
        name: "Saniya Devi",
        orderDate: "23rd May 2024",
        orderTotal: "$812.59",
        shippingAdress: "Tenali Nagar, Gurgaon 44425",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "#14",
        product_id: "#1259",
        name: "Narayan Sukdeve",
        orderDate: "7th May 2024",
        orderTotal: "$235.69",
        shippingAdress: "Kusam Nagar, Gurgaon 44232",
        orderStatus: "DELIVERED",
    },
    {
        id: "#15",
        product_id: "#5481",
        name: "Shital Naik",
        orderDate: "25th May 2024",
        orderTotal: "$654.68",
        shippingAdress: "Laxmi Nagar, Gurgaon 41972",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "#16",
        product_id: "#6345",
        name: "Rushi Carrol",
        orderDate: "29th May 2024",
        orderTotal: "$482.26",
        shippingAdress: "Telecom Nagar, Gurgaon 44232",
        orderStatus: "DELIVERED",
    },
    {
        id: "#17",
        product_id: "#2103",
        name: "Rihana Patel",
        orderDate: "29th May 2024",
        orderTotal: "$30.26",
        shippingAdress: "Abhyankar Nagar, Nagpur 440023",
        orderStatus: "DELIVERED",
    },
    {
        id: "#18",
        product_id: "#6324",
        name: "Akrant Sahu",
        orderDate: "23rd April 2024",
        orderTotal: "$593.24",
        shippingAdress: "Kahipura, Hhyderabad 47421",
        orderStatus: "DELIVERED",
    },
    {
        id: "#19",
        product_id: "#1628",
        name: "Pratap Kadu",
        orderDate: "28th May 2024",
        orderTotal: "$521.96",
        shippingAdress: "Ashish Nagar, Sambalpur 74588",
        orderStatus: "DELIVERED",
    },
    {
        id: "#20",
        product_id: "#9632",
        name: "Sahil Yadav",
        orderDate: "24th April 2024",
        orderTotal: "$623.25",
        shippingAdress: "Manewada, Nagpur 48751",
        orderStatus: "DELIVERED",
    },
    {
        id: "#21",
        product_id: "#8963",
        name: "Sai Badjata",
        orderDate: "25th April 2024",
        orderTotal: "$485.89",
        shippingAdress: "Lasun Nagar, Banglore 49367",
        orderStatus: "DELIVERED",
    },
    {
        id: "#22",
        product_id: "#6527",
        name: "Arvind Rai",
        orderDate: "15th April 2024",
        orderTotal: "$853.36",
        shippingAdress: "Jaiprakash Nagar, Nagpur 442103",
        orderStatus: "DELIVERED",
    },
    {
        id: "#23",
        product_id: "#7458",
        name: "Vasu Kahipura",
        orderDate: "1st March 2024",
        orderTotal: "$785.36",
        shippingAdress: "Pande Layout, Indore 36931",
        orderStatus: "DELIVERED",
    },
    {
        id: "#24",
        product_id: "#8671",
        name: "Priya Zansari",
        orderDate: "7th March 2024",
        orderTotal: "$783.59",
        shippingAdress: "Momimpura, Guwahati 58469",
        orderStatus: "DELIVERED",
    },
    {
        id: "#25",
        product_id: "#2574",
        name: "Raju Ghumade",
        orderDate: "5th March 2024",
        orderTotal: "$111.59",
        shippingAdress: "Vaishali Nagar, nagpur 45465",
        orderStatus: "DELIVERED",
    },
    {
        id: "#26",
        product_id: "#1012",
        name: "Urvashi Balsagar",
        orderDate: "23rd March 2024",
        orderTotal: "$965.02",
        shippingAdress: "Varsha Nagar, Varora 44582",
        orderStatus: "DELIVERED",
    },
    {
        id: "#27",
        product_id: "#8745",
        name: "Shailesh Ramapure",
        orderDate: "14th February 2024",
        orderTotal: "$784.69",
        shippingAdress: "Ramdaspeth, Kamptee 447841",
        orderStatus: "DELIVERED",
    },
    {
        id: "#28",
        product_id: "#1112",
        name: "Mohini Tembure",
        orderDate: "1th January 2024",
        orderTotal: "$125.25",
        shippingAdress: "Subhash Nagar, Raipur 47856",
        orderStatus: "DELIVERED",
    },
]