export const RecentOrderData = [
    {
        id: "ORD-1",
        name: "Shaili Zhodape",
        orderDate: "19th August 2024",
        orderTotal: "$759.26",
        shippingAdress: "151A, Omkar Nagar, Nagpur 48723",
        orderStatus: "PLACED",
    },
    {
        id: "ORD-2",
        name: "Riya Badhe",
        orderDate: "9th August 2024",
        orderTotal: "$532.36",
        shippingAdress: "23, Gandhi Bagh, Nagpur 44789",
        orderStatus: "CONFIRMED",
    },
    {
        id: "ORD-3",
        name: "Rajesh Sonavane",
        orderDate: "7th August 2024",
        orderTotal: "$42.36",
        shippingAdress: "Bulding No 78, Sikash Nagar, Firozpur 74589",
        orderStatus: "SHIPPED",
    },
    {
        id: "ORD-4",
        name: "Giriraj Sharma",
        orderDate: "28th July 2024",
        orderTotal: "$485.19",
        shippingAdress: "Flat No 72E, Gajanan Nagar, Gurgaon 44582",
        orderStatus: "OUT FOR DELIVERY",
    },  
    {
        id: "ORD-5",
        name: "Yash Bunny",
        orderDate: "8th June 2024",
        orderTotal: "$0.26",
        shippingAdress: "157A, B-1, Surve Nagar, Gurgaon 44582",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-6",
        name: "Abhilasha Barod",
        orderDate: "9th June 2024",
        orderTotal: "$789.42",
        shippingAdress: "16, Amdarnivas, Sahu Nagar, Delhi 47854",
        orderStatus: "SHIPPED",
    },
    {
        id: "ORD-7",
        name: "Sakshi Haste",
        orderDate: "10th June 2024",
        orderTotal: "$142.56",
        shippingAdress: "23, Atp Marg, Suyesh Nagar, Kaniha 89652",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "ORD-8",
        name: "Rutvik Shinde",
        orderDate: "16th June 2024",
        orderTotal: "$236.02",
        shippingAdress: "Rajesh Nagar, Hydeabad 74523",
        orderStatus: "SHIPPED",
    },
    {
        id: "ORD-9",
        name: "Gayatri Kulkarni",
        orderDate: "8th June 2024",
        orderTotal: "$0.26",
        shippingAdress: "83, Surve Nagar, Gurgaon 44582",
        orderStatus: "CONFIRMED",
    },
    {
        id: "ORD-10",
        name: "Sangul Abdur",
        orderDate: "13h May 2024",
        orderTotal: "$75.26",
        shippingAdress: "1002, Ashish Nagar, Gurgaon 36571",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "ORD-11",
        name: "Sayadi Rathod",
        orderDate: "15th May 2024",
        orderTotal: "$412.89",
        shippingAdress: "Suite 10, Kothavri, Talcher 58493",
        orderStatus: "SHIPPED",
    },
    {
        id: "ORD-12",
        name: "Rahul Parteki",
        orderDate: "23rd May 2024",
        orderTotal: "$482.23",
        shippingAdress: "1209, Shanto Nagar, Gurgaon 44215",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-13",
        name: "Saniya Devi",
        orderDate: "23rd May 2024",
        orderTotal: "$812.59",
        shippingAdress: "Tenali Nagar, Gurgaon 44425",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "ORD-14",
        name: "Narayan Sukdeve",
        orderDate: "7th May 2024",
        orderTotal: "$235.69",
        shippingAdress: "Apt 804, Kusam Nagar, Gurgaon 44232",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-15",
        name: "Shital Naik",
        orderDate: "25th May 2024",
        orderTotal: "$654.68",
        shippingAdress: "PO Box 29109, Laxmi Nagar, Gurgaon 41972",
        orderStatus: "OUT FOR DELIVERY",
    },
    {
        id: "ORD-16",
        name: "Rushi Carrol",
        orderDate: "29th May 2024",
        orderTotal: "$482.26",
        shippingAdress: "3rd Marg, Telecom Nagar, Gurgaon 44232",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-17",
        name: "Rihana Patel",
        orderDate: "29th May 2024",
        orderTotal: "$30.26",
        shippingAdress: "Suite 5, Abhyankar Nagar, Nagpur 440023",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-18",
        name: "Akrant Sahu",
        orderDate: "23rd April 2024",
        orderTotal: "$593.24",
        shippingAdress: "Suite 65, Kahipura, Hhyderabad 47421",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-19",
        name: "Pratap Kadu",
        orderDate: "28th May 2024",
        orderTotal: "$521.96",
        shippingAdress: "17 Marg, Ashish Nagar, Sambalpur 74588",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-20",
        name: "Sahil Yadav",
        orderDate: "24th April 2024",
        orderTotal: "$623.25",
        shippingAdress: "C-1 Asav Apartment, Manewada, Nagpur 48751",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-21",
        name: "Sai Badjata",
        orderDate: "25th April 2024",
        orderTotal: "$485.89",
        shippingAdress: "5th Floor, Lasun Apartment, Banglore 49367",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-22",
        name: "Arvind Rai",
        orderDate: "15th April 2024",
        orderTotal: "$853.36",
        shippingAdress: "18 Aparna, Jaiprakash Nagar, Nagpur 442103",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-23",
        name: "Vasu Kahipura",
        orderDate: "1st March 2024",
        orderTotal: "$785.36",
        shippingAdress: "Suite 62, High Court, Pande Layout, Indore 36931",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-24",
        name: "Priya Zansari",
        orderDate: "7th March 2024",
        orderTotal: "$783.59",
        shippingAdress: "Apt 1857, Momimpura, Guwahati 58469",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-25",
        name: "Raju Ghumade",
        orderDate: "5th March 2024",
        orderTotal: "$111.59",
        shippingAdress: "Suyog Marg, Vaishali Nagar, nagpur 45465",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-26",
        name: "Urvashi Balsagar",
        orderDate: "23rd March 2024",
        orderTotal: "$965.02",
        shippingAdress: "House 1126, Varsha Nagar, Varora 44582",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-27",
        name: "Shailesh Ramapure",
        orderDate: "14th February 2024",
        orderTotal: "$784.69",
        shippingAdress: "Maharaj Bagh, Ramdaspeth, Kamptee 447841",
        orderStatus: "DELIVERED",
    },
    {
        id: "ORD-28",
        name: "Mohini Tembure",
        orderDate: "1th January 2024",
        orderTotal: "$125.25",
        shippingAdress: "Suite 6, Anderi West Mumbai 462510",
        orderStatus: "DELIVERED",
    },
]